// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/5/7 下午3:37:40
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/project/map_app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/plugins/**/*.{js,ts,mjs}","C:/project/map_app/composables/**/*.{js,ts,mjs}","C:/project/map_app/utils/**/*.{js,ts,mjs}","C:/project/map_app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/project/map_app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;